### PR TITLE
Updated Readme with CUDA 9 compilation.

### PR DESCRIPTION
**Pull request by dwillcox**
Let me know if there's anything to add about CUDA 9.

### CODE REVIEW

**Comment by maximumcats** [comment]
> Only the PGI Fortran compiler supports CUDA Fortran.

Actually the IBM compiler does too... it doesn't currently compile though, which I'm working on right now.

> To compile with CUDA 8, use the following modules:

Also you need to use the CUDA_VERSION=8.0 at make time.

**Comment by dwillcox** [comment]
I seem to recall jsrun for StarLord came up recently on Slack so I added a few example commands.

**Comment by maximumcats** [comment]
With the latest gpu branch of amrex, IBM should compile StarLord now.

**Comment by maximumcats** [comment]
Also, you might want to note that if you leave off the -r option for jsrun, it will still do the intelligent thing of divide up the 16 ranks among the 4 nodes equally.

**Pull request merged**
